name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        go: ["^1.17"]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    name: Go ${{ matrix.go }} in ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/setup-go@v2
        with:
          stable: '!contains(${{ matrix.go }}, "beta") && !contains(${{ matrix.go }}, "rc")'
          go-version: ${{ matrix.go }}

      - name: Environment
        run: |
          go version
          go env

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          args: --timeout=5m30s
          skip-go-installation: true

      - name: Format
        run: make format-check

      - name: Test
        run: |
          make test
